'use client';

import { useState } from 'react';

const areas: Record<string, string[]> = {
  Visakhapatnam: ['MVP Colony', 'Madhurawada', 'Gajuwaka', 'Siripuram', 'Seethammadhara', 'Beach Road'],
  Vijayawada: ['Benz Circle', 'Poranki', 'Governorpet', 'Kanuru', 'Patamata'],
  Hyderabad: ['Madhapur', 'Kondapur', 'Kukatpally', 'Gachibowli', 'Miyapur'],
  Bengaluru: ['Whitefield', 'Indiranagar', 'Jayanagar', 'HSR Layout', 'Yelahanka'],
  Chennai: ['Adyar', 'Anna Nagar', 'Velachery', 'Tambaram', 'OMR'],
  Other: ['Other area'],
};

export default function Home() {
  const [city, setCity] = useState('');
  const [sent, setSent] = useState(false);
  const [files, setFiles] = useState<string[]>([]);
  const [menuOpen, setMenuOpen] = useState(false);

  function submitForm(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSent(true);
  }

  return <>
    <header className="topbar"><a className="brand" href="#home" aria-label="Instrctr home"><span className="brand-mark"><svg viewBox="0 0 42 42" aria-hidden="true"><circle cx="21" cy="21" r="19"/><path d="M5.5 24h12l2-5h7l3 5h7v5h-2.5a3 3 0 0 1-6 0h-8a3 3 0 0 1-6 0h-8z"/><path d="m16 24 3.5-5 4 5M27 19h2l2 5M20 14h6l3 3h-9z"/></svg></span><span>instrctr<span className="brand-dot">.</span></span></a>
      <button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">☰</button>
      <nav className={menuOpen ? 'nav open' : 'nav'}><a href="#services" onClick={() => setMenuOpen(false)}>Our services</a><a href="#impact" onClick={() => setMenuOpen(false)}>Our impact</a><a href="#cities" onClick={() => setMenuOpen(false)}>Where we are</a><a className="nav-cta" href="#join" onClick={() => setMenuOpen(false)}>Teach with us <span>↗</span></a></nav>
    </header>
    <main id="home">
      <section className="hero">
        <div className="hero-copy"><div className="eyebrow"><span className="pulse"/> DRIVING CLASSES, MADE HUMAN</div>
          <h1>Your road.<br/><span>Your rules.</span></h1>
          <p className="hero-text">Learn to drive with patient, trusted instructors who meet you where you are. A calmer way to get behind the wheel is on its way.</p>
          <div className="hero-actions"><a className="button primary" href="#services">Explore our services <span>↗</span></a><a className="text-link" href="#join">Are you a trainer? <span>→</span></a></div>
          <div className="proof"><span className="avatars"><i>✦</i><i>✦</i><i>✦</i></span><span>Building confident drivers, one lesson at a time</span></div>
        </div>
        <div className="hero-art"><div className="art-sun"/><div className="art-word">GO<br/>YOUR<br/>WAY<span>↗</span></div><div className="art-road"><div className="road-line"/><div className="car">▰</div></div><div className="art-tag"><span className="tag-icon">✳</span><span><b>Confidence starts here</b><small>Expert guidance. Your pace.</small></span></div><div className="art-stamp">INSTRCTR<br/>DRIVE YOUR<br/>OWN STORY</div></div>
        <div className="hero-bottom"><span>01 / 04</span><div className="hero-progress"><i/></div><span>GET MOVING</span></div>
      </section>
      <section id="services" className="section services"><div className="section-heading"><div><div className="eyebrow">THE RIGHT START, YOUR WAY</div><h2>Every kind of driver<br/>starts somewhere.</h2></div><p>From your first nervous turn to confident city driving, find the kind of guidance that feels right for you.</p></div>
        <div className="service-grid"><article className="service-card scooter"><div className="service-top"><span className="service-number">01 — TWO WHEELS</span><span className="round-arrow">↗</span></div><div className="service-illustration photo-frame"><img src="/images/scooter-lesson.png" alt="A learner and instructor practicing on a scooter by the coast"/><span className="photo-caption">SCOOTER LESSONS · VISAKHAPATNAM</span></div><div><h3>Scooter &amp; bike lessons</h3><p>Build your balance, find your rhythm, and ride with confidence.</p></div><div className="service-foot"><span>Patient, step-by-step coaching</span><span>↗</span></div></article>
        <article className="service-card car-service"><div className="service-top"><span className="service-number">02 — FOUR WHEELS</span><span className="round-arrow">↗</span></div><div className="service-illustration photo-frame"><img src="/images/car-lesson.png" alt="A learner practicing in a car with an instructor beside her"/><span className="photo-caption">CAR LESSONS · LEARN AT YOUR PACE</span></div><div><h3>Car driving lessons</h3><p>Get comfortable in the driver’s seat with an expert by your side.</p></div><div className="service-foot"><span>Manual &amp; automatic options</span><span>↗</span></div></article>
        <article className="service-card confidence"><div className="service-top"><span className="service-number">03 — YOU’RE IN CONTROL</span><span className="round-arrow">↗</span></div><div className="confidence-art"><div className="confidence-star">✳</div><span>NO RUSH.<br/>NO JUDGEMENT.<br/><b>JUST YOU.</b></span></div><div><h3>A pace that feels like yours</h3><p>Friendly instructors, flexible learning, and room to grow at your own speed.</p></div><div className="service-foot"><span>Learning built around you</span><span>↗</span></div></article></div>
      </section>
      <section className="impact" id="impact"><div className="impact-inner"><div className="impact-title"><div className="eyebrow light">A LITTLE PROOF GOES A LONG WAY</div><h2>Good driving<br/>changes everything.</h2><p>And it starts with the people who teach it. We’re building a community that helps more people move through life with confidence.</p><a href="#join" className="button light-button">Be part of it <span>↗</span></a></div><div className="stats"><div className="stat"><span className="stat-icon">✳</span><strong>36<span>+</span></strong><b>driving experts</b><small>Ready to guide your journey</small></div><div className="stat"><span className="stat-icon">↗</span><strong>2.4<span>k</span></strong><b>learners empowered</b><small>And many more to come</small></div><div className="stat"><span className="stat-icon">⌖</span><strong>8</strong><b>cities and growing</b><small>Local expertise, near you</small></div></div></div><div className="impact-note">THE ROAD IS BETTER WHEN WE TAKE IT TOGETHER <span>✳</span></div></section>
      <section id="cities" className="cities section"><div className="cities-copy"><div className="eyebrow">LOCAL KNOW-HOW, RIGHT AROUND THE CORNER</div><h2>Rooted in your<br/>neighbourhood.</h2><p>Our instructor community is growing across India. We pair local road knowledge with a learning experience designed around you.</p><a href="#join" className="text-link">Find your city <span>→</span></a></div><div className="city-map"><div className="map-lines"><i/><i/><i/><i/><i/><i/></div><span className="map-label label-one">VISAKHAPATNAM</span><span className="map-label label-two">HYDERABAD</span><span className="map-label label-three">BENGALURU</span><span className="map-label label-four">CHENNAI</span><span className="map-label label-five">VIJAYAWADA</span><span className="map-pin pin-one">✳</span><span className="map-pin pin-two">✳</span><span className="map-pin pin-three">✳</span><span className="map-pin pin-four">✳</span><span className="map-pin pin-five">✳</span><div className="map-caption"><b>Growing together</b><span>More cities, more possibilities.</span></div></div></section>
      <section className="join" id="join"><div className="join-inner"><div className="join-copy"><div className="eyebrow light">FOR THE PEOPLE WHO MAKE IT POSSIBLE</div><h2>Good at teaching?<br/><span>Let’s get moving.</span></h2><p>Bring your experience to a community that puts learners first. Tell us a little about yourself and we’ll be in touch.</p><div className="join-points"><div><span>01</span>Flexible teaching opportunities</div><div><span>02</span>Meet learners in your area</div><div><span>03</span>Grow with a driving-first community</div></div><div className="join-decoration">i<span>n</span>.</div></div>
        <div className="form-card"><div className="form-heading"><span>INSTRUCTOR APPLICATION</span><b>Let’s start with you.</b><small>Fields marked * are required.</small></div>{sent ? <div className="success"><span>✓</span><h3>Thanks for raising your hand!</h3><p>Your details are ready. Our team will be in touch soon.</p><button onClick={() => setSent(false)}>Submit another response</button></div> : <form onSubmit={submitForm}><div className="form-row"><label>Full name *<input name="name" placeholder="e.g. Alex Kumar" required /></label><label>Phone number *<input name="phone" type="tel" placeholder="+91 98765 43210" required /></label></div><label>Email address *<input name="email" type="email" placeholder="you@example.com" required /></label><div className="form-row"><label>City *<select required value={city} onChange={e => setCity(e.target.value)}><option value="" disabled>Select your city</option>{Object.keys(areas).map(name => <option key={name}>{name}</option>)}</select></label><label>Area / neighbourhood *<select required disabled={!city}><option value="" disabled selected>{city ? 'Select your area' : 'Choose a city first'}</option>{(areas[city] || []).map(area => <option key={area}>{area.trim()}</option>)}</select></label></div><fieldset><legend>What would you like to teach? *</legend><div className="choices"><label><input type="checkbox" name="vehicle" value="car"/> <span>🚘</span> Car</label><label><input type="checkbox" name="vehicle" value="two-wheeler"/> <span>🛵</span> Two-wheeler</label></div></fieldset><label>Driving licence number *<input name="licence" placeholder="Enter your licence number" required /></label><label className="upload-label">Upload your driving licence *<div className="upload"><span className="upload-icon">↑</span><span><b>Choose a file</b> or drag it here<small>JPG, PNG or PDF · Max 10 MB</small></span><input type="file" required accept="image/*,.pdf" onChange={e => setFiles(Array.from(e.target.files || []).map(f => f.name))}/></div>{files.length > 0 && <small className="file-name">✓ {files.join(', ')}</small>}</label><label className="checkline"><input type="checkbox" required/> I agree to be contacted about instructor opportunities.</label><button className="button submit" type="submit">Send my application <span>↗</span></button><p className="privacy">Your information stays with us. We’ll only use it to follow up on your application.</p></form>}</div>
      </div></section>
      <section className="app-banner"><div className="app-spark">✳</div><div><div className="eyebrow">YOUR NEXT MOVE IS ALMOST HERE</div><h2>The Instrctr app is coming soon.</h2><p>Driving classes, local experts, and your learning journey — all in one place.</p></div><div className="store-buttons"><span className="store-badge"><span className="store-icon">▶</span><span><small>COMING SOON TO</small><b>Google Play</b></span></span><span className="store-badge"><span className="apple-icon">●</span><span><small>COMING SOON TO</small><b>App Store</b></span></span></div></section>
    </main>
    <footer><div className="footer-main"><div className="footer-brand"><a className="brand" href="#home"><span className="brand-mark"><svg viewBox="0 0 42 42"><circle cx="21" cy="21" r="19"/><path d="M5.5 24h12l2-5h7l3 5h7v5h-2.5a3 3 0 0 1-6 0h-8a3 3 0 0 1-6 0h-8z"/><path d="m16 24 3.5-5 4 5M27 19h2l2 5M20 14h6l3 3h-9z"/></svg></span><span>instrctr<span className="brand-dot">.</span></span></a><p>Learn with confidence.<br/>Drive with freedom.</p></div><div><b>EXPLORE</b><a href="#services">Our services</a><a href="#impact">Our impact</a><a href="#cities">Cities</a></div><div><b>JOIN US</b><a href="#join">Become an instructor</a><a href="#join">Partner with Instrctr</a></div><div className="footer-app"><b>COMING SOON</b><p>Your next journey, in your pocket.</p><div className="footer-stores"><span>▶ Google Play</span><span>● App Store</span></div></div></div><div className="footer-bottom"><span>© 2026 Instrctr. All roads lead somewhere.</span><span>MADE FOR THE ROAD <b>✳</b></span></div></footer>
  </>;
}
